#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/stat.h>

int main(int argc, char* argv[])
{
    int nbVar, nbClause, clauseSize, nbFiles, i, k, f;
    char filename[1000], testFilename[1000], dirname[1000];
    if (argc < 5)
    {
        printf("Pas assez d'arguments\n");
        return -1;
    }

    nbVar = atoi(argv[1]);
    nbClause = atoi(argv[2]);
    clauseSize = atoi(argv[3]);
    nbFiles = atoi(argv[4]);
    srandom(time(NULL));
    
    sprintf(dirname, "tests-%d-%d-%d-%d/", nbVar, nbClause, clauseSize, nbFiles);

    sprintf(filename, "batch-%d-%d-%d-%d.sh", nbVar, nbClause, clauseSize, nbFiles);
    freopen(filename, "w+", stdout);
    printf("#!/bin/bash\n");
    printf("for i in %s", dirname);
    printf("*.cnf\ndo\n");
    printf(" echo $i\n$* $i\ndone\nexit 0");
    
    chmod(filename, S_IRWXU);
    
    sprintf(testFilename, "tests-%d-%d-%d-%d.sh", nbVar, nbClause, clauseSize, nbFiles);
    freopen(testFilename, "w+", stdout);
    printf("#!/bin/bash\n");
    printf("for i in %s", dirname);
    printf("*.cnf\ndo\n");
    printf("minisatOutput= minisat $i > /dev/null\n");
    printf("exeOutput= $* $i > /dev/null\n");
    printf("if [$minisatOutput -ne $exeOutput]\nthen\necho \"ERREUR: SAT/UNSAT\"\nelif [$minisatOutput -e 10]\nthen\n");
    printf("$* $i > $i$\".out\"\ncat $i $i$\".out\" | ./verif\nrm $i$\".out\"\nfi\ndone\nexit 0");
    chmod(testFilename, S_IRWXU);    


    mkdir(dirname, S_IRWXU); 
    for (f = 0; f < nbFiles; f++)
    {
        sprintf(filename, "%stest-%d-%d-%d-%d.cnf", dirname, nbVar, nbClause, clauseSize, f);
        freopen(filename, "w+", stdout); 
    
        printf("c Auto-generated by J. Le Maire and A. Talon\n");
        printf("p cnf %d %d\n", nbVar, nbClause);
        for (i = 0; i < nbClause; i++)
        {
            for (k = 0; k < clauseSize; k++)
                printf("%s%ld ", random()%2 ? "-":"", random()%nbVar+1);
            printf("0\n");

        }
     }

    return 0;
}
